### ISSUE TITLE
Failed to load the git-wip package

### ISSUE THREAD

**Issue by winstliu** [coopermaruyama/atom-git-wip#1] opened 2015-06-03 21:30 UTC
_From @athompson-r7 on June 3, 2015 21:18_
1. Error below is produced when starting atom

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core
### Stack Trace

Failed to load the git-wip package

```
At missing '

[stdin]:12:18: error: missing '
  'alt-cmd-g w': 'git-wip:add-project-checkpoint
                 ^
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete",
      "autocomplete-ruby",
      "autocomplete-plus"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 10
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.6
atom-lint, v0.20.1
editorconfig, v1.0.0
git-log, v0.4.1
git-wip, v0.1.1
language-chef, v0.4.0
language-groovy, v0.4.0
linter-foodcritic, v0.3.9
minimap, v4.9.2
minimap-find-and-replace, v4.2.0
vim-mode, v0.50.0

# Dev
No dev packages
```

_Copied from original issue: atom/atom#7093_

**Comment by czxtm** [comment] 2015-06-04 02:32
Thanks for reporting. Even though we've updated all deprecated calls, it looks like some other atom 1.0 updates have caused some regression.. This specific error has been fixed in fcc5cd195d509c15aaf5a39d3a09f858940123d4 , however there are some other issues as well now which I'm still working on so in the meantime I've pushed it to the develop branch if you want to try that.

Closing this and tracking other issues in a separate issue.

**Closed as completed by czxtm** 2015-06-04 02:32 UTC
Labels: bug
